\c games_dev;

INSERT INTO games (title, price, description, release, platforms, genres, developers,autisic, image, rating) 
VALUES
 ( 'Cyberpunk2077', '59.99', 'Cyberpunk 2077 is an open world, action adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one of a kind implant that is the key to immortality.', '12/10/2020', 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One', 'RPG', 'CD PROJECT RED, CD PROJECT','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/Cyberpunk_2077_box_art_exbfnh.jpg', 4),
( 'Battlefield V','29.99', 'The Battlefield series goes back to its roots in a never before seen portrayal of World War 2. Take on physical, all out multiplayer with your squad in modes like the vast Grand Operations and the cooperative Combined Arms, or witness human drama set against global combat in the single player War Stories. As you fight in epic, unexpected locations across the globe, enjoy the richest and most immersive Battlefield yet.', '11/9/2018', 'Playstation 4, PC, Xbox Series S/X, Xbox One', 'Shooter', 'EA Digital Illusions CE', 'false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423519/knyiQNrzbp6tEe8t04AYRhhJUF5wLIGO_xuev3d.jpg', 3),
( 'Life is Strange','14.99', 'Life Is Strange is a five part episodic game that sets out to revolutionize story based choice and consequence games by allowing the player to rewind time and affect the past, present, and future. You are Max, a photography senior who saves her old friend Chloe by discovering she can rewind time.', '01/30/2015', 'Playstation 4, PC, Xbox One, Xbox 360, Playstation 3', 'Adventure', 'Dontnod Entertainment', 'false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/capsule_616x353_d1pnj4.jpg', 4),
( 'Red Dead Redemption 2','34.99', 'After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.', '10/26/2018', 'Xbox One, PlayStation 4, PC, Google Stadia', 'RPG', 'Rockstar Studios', 'false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/header_vdwfkt.jpg', 5),
( 'Horizon Zero Dawn','29.99', 'Horizon Zero Dawn takes place in the 31st century, in a post apocalyptic world where colossal machines dominate the land. Human civilization has regressed to tribal societies of hunters and gatherers who survive in immense forests, imposing mountain ranges, and the atmospheric ruins of their ancestors – all while the machines become increasingly powerful. The player controls Aloy, a huntress who uses her speed, cunning, and agility to stay alive and protect herself and others against the force, size, and power of the machines. The game features sci fi and mythical elements.', '02/28/2017', 'PlayStation 4, PC', 'Adventure', 'Guerrilla Games', 'false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/capsule_616x353_1_se6kpy.jpg', 4),
 ( 'The Elder Scrolls: Skyrim','19.99', 'The Elder Scrolls V: Skyrim is an action role playing game, playable from either a first  or third person perspective. The player may freely roam over the land of Skyrim, an open world environment consisting of wilderness expanses, dungeons, caves, cities, towns, fortresses, and villages.', '11/10/2011', 'Xbox 360, PC (Microsoft Windows), PlayStation 3', 'RPG', 'Bethesda Game Studios','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/elder-scrolls-skyrim-button-2017-1629409446732_fexpsy.jpg', 4),
( 'Rise of the Tomb Raider','12.99', 'Rise of the Tomb Raider is a third person action adventure game in which players control Lara Croft, who is on a quest to discover the legendary city of Kitezh. Combat is a major gameplay mechanic; Lara has a large variety of weapons at her disposal (including assault rifles, shotguns, and pistols), some of which have an alternate firing mode. Players may also utilize stealth to progress through portions of the game, using bows and arrows to take out enemies, creating distractions to draw enemy attention away from Lara, or hiding in bushes to evade enemies. Lara can use the environment to fight enemies, shooting explosive barrels, tearing down rope wrapped structures with rope arrows, or ambushing enemies from high ground. She can also use her ice axe and combat knife to engage in melee combat with enemies.', '11/10/2015', 'Xbox One, PlayStation 4, Linux, Xbox 360, Mac, PC, Google Stadia', 'Adventure', 'Crystal Dynamics','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/header_1_yb4noj.jpg', 4),
( 'Terraria','14.99', 'Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever evolving gear, machinery, and aesthetics? Perhaps you will choose instead to seek out ever greater foes to test your mettle in combat? Maybe you will decide to construct your own city to house the host of mysterious allies you may encounter along your travels? In the World of Terraria, the choice is yours!', '05/16/2011', 'A lot.', 'Adventure', 'Re Logic','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/header_2_kf4fon.jpg', 3),
( 'The Witcher 3: Wild Hunt','19.99', 'RPG and sequel to The Witcher 2 (2011), The Witcher 3 follows witcher Geralt of Rivia as he seeks out his former lover and his young subject while intermingling with the political workings of the wartorn Northern Kingdoms. Geralt has to fight monsters and deal with people of all sorts in order to solve complex problems and settle contentious disputes, each ranging from the personal to the world changing.', '05/19/2015', 'Xbox One, PlayStation 4, PC, Nintendo Switch', 'RPG', 'CD PROJECT RED','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423519/The_Witcher_3-_Wild_Hunt_omupkv.jpg', 5),
( 'Fallout 4','26.99', 'The story of Fallout 4 focuses on a spouse, the Sole Survivor of Vault 111, as they search for their missing child, Shaun. Fallout 4 is set in and around the Boston area in 2287, 10 years after Fallout 3. Along the way, the Sole Survivor discovers a world in fear of a mysterious organization known as the Institute, consumed by paranoia of a race of robotic yet also biological human like beings known as synths. As a result of the synth focused narrative, the Sole Survivor, as well as the player, are faced with ethical questions such as how far people should experiment with science, the morality of creating sentient living machines that express emotions and suffering, and what it means to be human.', '11/10/2015', 'Xbox One, PlayStation 4, PC', 'RPG', 'Bethesda Game Studios','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/Fallout_4_hw27mb.jpg',3),
( 'God of War','41.99', 'Many years have passed since Kratos took his vengeance against the Olympian gods. Having survived his final encounter with his father Zeus, Kratos has since travelled to Midgard in Ancient Norway and now lives with his young son Atreus in the world of the Norse gods, a savage land inhabited by many ferocious monsters and warriors. In order to teach his son, whose mother (and Kratoss second wife) has recently died, how to survive in such a world, Kratos must master the rage that has driven him for many years and embrace his newfound role as a father and a mentor.', '04/20/2018', 'PlayStation 4, PC', 'Adventure', 'Santa Monica Studio','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/godOfWar_rum0ht.jpg', 5),
( 'Half Life 2','11.99', '1998. HALF LIFE sends a shock through the game industry with its combination of pounding action and continuous, immersive storytelling. By taking the suspense, challenge and visceral charge of the original, and adding startling new realism and responsiveness, Half Life 2 opens the door to a world where the players presence affects everything around them, from the physical environment to the behaviors even the emotions of both friends and enemies.', '11/16/2004', 'Android, Linux, Xbox 360, Mac, Xbox, PC, PlayStation 3', 'Shooter', 'Valve','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/capsule_616x353_2_uxryec.jpg', 5),
( 'The Walking Dead: S1','6.99', 'Play as Lee Everett, a convicted criminal, who has been given a second chance at life in a world devastated by the undead. With corpses returning to life and survivors stopping at nothing to maintain their own safety, protecting an orphaned girl titled Clementine may offer him redemption in a world gone to hell.', '04/12/2012', 'Android, Xbox One, PlayStation 4, Xbox 360, PC, Nintendo Switch, PlayStation 3', 'Adventure', 'Telltale Games','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423520/unnamed_vyp8om.png', 4),
( 'Counter Strike: GO','4.99', 'The game pits two teams, Terrorists and Counter Terrorists, against each other in different objective based game modes. The most common game modes involve the Terrorists planting a bomb while Counter Terrorists attempt to stop them, or Counter Terrorists attempting to rescue hostages that the Terrorists have captured.', '08/21/2012', 'Linux, Xbox 360, Mac, PC, PlayStation 3', 'Shooter', 'Valve / Hidden Path Entertainment','false', 'https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/capsule_616x353_3_mn1erz.jpg', 4),
 ( 'Minecraft','25.99', 'Minecraft is a video game in which players create and break apart various kinds of blocks in three-dimensional worlds. The game is two main modes are Survival and Creative. In Survival, players must find their own building supplies and food. They also interact with blocklike mobs, or moving creatures.', '08/15/2011', 'Android, Linux, Mac, PC', 'Adventure', 'Mojang','true', 'https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188606/minecraft_iuejtm.jpg', 4
),
( 'Golf with your Friends','7.99', 'Golf With Your Friends is an entertaining, challenging, multiplayer mini golf game for up to 12 players. The controls are simple and the game is designed for the user to be able to host or join a game within a few seconds.', '01/29/2016', 'Xbox One, PlayStation 4, Linux, PC, Nintendo Switch, Google Stadia', 'Sports', 'Blacklight Interactive','true', 'https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188609/golfwithyourfriends_rxrsbv.jpg', 2
),
( 'Rocket League','23.99', 'Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition. Rocket League includes casual and competitive Online Matches, a fully-featured offline Season Mode, special “Mutators” that let you change the rules entirely, hockey and basketball-inspired Extra Modes, and more than 500 trillion possible cosmetic customization combinations.', '07/07/2015', 'Xbox One, PlayStation 4, Linux, Mac, PlayStation 5, PC, Nintendo Switch, Xbox Series S/X', 'Sports', 'Psyonix','true', 'https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188608/rocketleague_on6yqd.jpg', 4
),
( 'Mario Kart 8: Deluxe','24.99', 'Deluxe includes five new battle mode-exclusive courses, and three battle courses adapted from previous entries in the Mario Kart series. These battle courses are designed specifically for the mode, featuring layouts that allow for easier item play, rather than repurposing standard race courses like Mario Kart 8.', '04/28/2017', 'Nintendo Switch', 'Racing', 'Nintendo EAD','true', 'https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658232678/mariokart_0_mhgbeg.jpg', 4
),
('Risk', '19.99','In the Risk game, the goal is simple: players aim to conquer their enemies territories by building an army, moving their troops in, and engaging in battle. Depending on the roll of the dice, a player will either defeat the enemy or be defeated.', '10/30/2018','Nintendo Switch', 'Party','ubisoft', 'true','https://res.cloudinary.com/dtabunojn/image/upload/v1676423519/hero_bm63fd.avif',  5
),
('Saints Row', '29.98', 'Set within the fictional city of Santo Ileso, loosely based on Las Vegas, the single-player story follows a group of four friends who start their own outlaw gang called The Saints, which they subsequently expand by seizing power from other criminal organizations in the city.', '08/23/2022', ' PC, Xbox One, Xbox Series X|S, PlayStation 4, and PlayStation 5.','Action', 'Deep Silver','true','https://res.cloudinary.com/dtabunojn/image/upload/v1676423519/Saints_Row_2022_Cover_Art_hzhrtu.jpg', 3
),
('Vampire: The Masquerade', '24.99','Vampire: The Masquerade is a tabletop RPG both intense and intimate to play, for it is a game of consequences. Delicious, dreadful consequences! In VTM, you play as supernatural beings both powerful and damaged, inextricably tied to the mortal world while cursed to never truly be part of it','06/14/2022', 'PlayStation 4, Nintendo Switch, PlayStation 5, Xbox Series X','Action','Big Bad Wolf','true','https://res.cloudinary.com/dtabunojn/image/upload/v1676423519/Swansong_Cover_vtusle.jpg', 3
),
('RollerCoaster Tycoon', '5.99','RollerCoaster Tycoon Deluxe takes you for a ride in the original RollerCoaster Tycoon and its expansion packs, Corkscrew Follies and Loopy Landscapes. Create the ultimate theme park using a variety of coaster types with giant loops and barrel rolls and in-park attractions like suspended monorails and water.', '05/31/1999','	Microsoft Windows, Xbox, macOS, iOS, Nintendo 3DS, Nintendo Switch, Android','Simulation', 'Chris Sawyer Productions','true','https://res.cloudinary.com/dtabunojn/image/upload/v1676423518/61KTPYDHJHL_a6w1ui.jpg', 2
)